### ISSUE TITLE
bug: It doesn't throw any error with status code 500+

### ISSUE THREAD

**Issue by mehrunrasoli** [IonicaBizau/scrape-it#123] opened 2018-12-13 14:39 UTC
After one hour of searching and debugging for why I can't get content of the given URL, I found that there is a `503 "Service Temporarily Unavailable"` in the response object which doesn't alert me at all.

Is it a bug?

**Comment by IonicaBizau** [comment] 2018-12-31 12:05
Duplicate of #112

**Closed by IonicaBizau** 2018-12-31 12:05 UTC
Labels: duplicate
