### ISSUE TITLE
How to get value and inner text of options in a select?

### ISSUE THREAD

**Issue by Natanael1234** [IonicaBizau/scrape-it#52] opened 2017-02-11 22:52 UTC
I need to get a list of value and inner of each item of a select.

How could I do this via scrape-it?

**Comment by IonicaBizau** [comment] 2017-02-16 05:03
Can you add an example?

**Comment by IonicaBizau** [comment] 2017-02-19 10:23
Closing due to no reply. Maybe duplicate of #45.

**Closed by IonicaBizau** 2017-02-19 10:23 UTC

**Comment by fedecia** [comment] 2017-05-05 06:36
This should do it
```js
$('div.classname').first().contents().filter(function() {
    return this.type === 'text';
}).text();
```
